### ISSUE TITLE
Container for 0.9.1 is not tagged with the version

### ISSUE THREAD

**Issue by elventear** [nats-io/nack#106]
I see that 2 days ago https://github.com/nats-io/nack/releases/tag/v0.9.1 was released, but in [Docker Hub](https://hub.docker.com/r/natsio/jetstream-controller/tags) that version was pushed as `latest`, but there is no version tag (e.g. `0.9.1`). This makes it harder to manage deployments based on versions.

**Comment by wallyqs** [comment]
Hi @elventear there was an issue with that image so we just yanked it, I'll post the issue and new tagged version in a bit.

**Comment by wallyqs** [comment]
New image is out, apologies for the inconvenience: https://github.com/nats-io/nack/releases/tag/v0.9.2
