### ISSUE TITLE
When installing according to the manual, jetstreams are NOT enabled

### ISSUE THREAD

**Issue by MDullak** [nats-io/nack#157]
### What version were you using?

helm chart:
NATS: 2.10.7
NACK: 0.14.1

### What environment was the server running in?

Clean debian 12 + k3sinstall

### Is this defect reproducible?

yes

### Given the capability you are leveraging, describe your expectation?

Running those:
helm repo add nats https://nats-io.github.io/k8s/helm/charts/
helm install nats nats/nats --set=nats.jetstream.enabled=true
helm install nack nats/nack --set jetstream.nats.url=nats://nats:4222

I would expect that NATS will be running with JetStreams.
Looking at the pod log this does not needs to be the case.
On top of that deploying sample stream and consumers results with error:
<code>
Status:
  Conditions:
    Last Transition Time:  2023-12-28T18:15:44.278033855Z
    Message:               failed to check if stream exists: nats: no responders available for request
    Reason:                Errored
    Status:                False
</code>

### Given the expectation, what is the defect you are observing?

I would expect that running basic install steps would give me the result like in the ReadMe.

I had to manuall add jetstreams to nats.conf (via ConfigMap).
And then it started to work.

**Comment by Jarema** [comment]
Hey.

I think that with new Helm Charts, it's 
https://github.com/nats-io/k8s/tree/main/helm/charts/nats#jetstream-cluster-on-3-separate-hosts

so it's under `config.jetstream.enabled`.
