### ISSUE TITLE
Error: "failed to connect to nats-servers(nats://nats:4222): nats: secure connection not available" while creating a stream in an account.

### ISSUE THREAD

**Issue by u-habiba** [nats-io/nack#184]
### What version were you using?

nats-server: v2.10.16

### What environment was the server running in?

Minikube cluster is being used for deployment.

Dokcer image: nats:2.6.2-alpine as mentioned in [this helm file](https://github.com/nats-io/nack/blob/main/examples/secure/nats-helm.yaml)

### Is this defect reproducible?

Following this [section](https://github.com/nats-io/nack#:~:text=The%20following%20is%20an%20example%20of%20how%20to%20get%20Accounts%20working%20with%20a%20custom%20NATS%20Server%20URL%20and%20TLS%20certificates) of documentation, at the following step to create a stream;
```
kubectl apply -f nack/nats-stream-foo-a.yaml
``` 

We get the error by describing the stream;
```
kubectl describe stream foo
```

Error is ; `failed to connect to nats-servers(nats://nats:4222): nats: secure connection not available`

### Given the capability you are leveraging, describe your expectation?

All of the required pods are running successfully, expected behavior should be that stream is created without an error and able to connect to nats server.

### Given the expectation, what is the defect you are observing?

Stream is not being created with the follwoing error. "failed to connect to nats-servers(nats://nats:4222): nats: secure connection not available"

**Comment by Jarema** [comment]
Can you please check the status of NATS deployment?
Are pods healthy?
