### ISSUE TITLE
Need to designate the NATS server or account to create a stream after deployed the jetstream controller

### ISSUE THREAD

**Issue by luotian-github** [nats-io/nack#21]
After deployed a jetstream controller, there is no parameter to specify the NATS server or account for a stream to create. Because the controller uses the fixed serverURL when initially deployed.
It is inconvenient when need to use different accounts/users to create streams. Have to update the  jetstream controller.

**Comment by wallyqs** [comment]
I was thinking that the jetstream controller should only have one identity since easy to deploy multiple controllers in k8s but maybe we could have some mode where it can use multiple contexts.

**Comment by luotian-github** [comment]
Thanks for your comment @wallyqs . In our use case, we are going to use 500-1000 accouts, if deploy so many controllers, it will consume a lot of resources.

**Comment by JackZxj** [comment]
Hi, I am doing something on this. I try to add the server info to the Stream/Consumer crd, which allows the controller to connect to a new nats-server using the new account.

**Comment by luotian-github** [comment]
There is a "servers" item in the nack/deploy/examples/streamtemplate.yml
apiVersion: jetstream.nats.io/v1beta1
kind: StreamTemplate
metadata:
  name: mystreamtemplate
spec:
  servers:
  - nats://localhost:4222

It seems that item could be used to designate the serverURL

**Comment by wallyqs** [comment]
Fixed via #23 + #42
