### ISSUE TITLE
Stream MaxBytes not set during create

### ISSUE THREAD

**Issue by jdolce** [nats-io/nack#40]
Looks like during a recent re-factor max bytes is no longer being set on stream creates.

https://github.com/nats-io/nack/blob/main/controllers/jetstream/stream.go#L163

Seems to be a result of this commit https://github.com/nats-io/nack/commit/74d1ddcf8c47d142f112ff63639e3529182f2145

**Comment by jdolce** [comment]
I took a look at changing this, which is a really simple change. However, I think some better tests are in order which will help catch these sorts of errors in the future. Would be nice to check the stream config after it has been created.

**Comment by wallyqs** [comment]
Current status of branch with e2e tests is here: https://github.com/nats-io/nack/commits/minikube

**Comment by variadico** [comment]
I'm thinking we should separate the two tasks here.
* The actual issue here could be solved with #60 
* The e2e tests can be tracked at https://github.com/nats-io/nack/issues/59
