### ISSUE TITLE
Jetstream Stream CRD requires mirror, sources and placement

### ISSUE THREAD

**Issue by drewcorlin1** [nats-io/nack#43]
When [these changes](https://github.com/nats-io/k8s/pull/332/files) were added to the Stream CRD, `mirror`, `sources` and `placement` became required fields. These changes mean previously working streams as well as the [ones suggested by the docs](https://docs.nats.io/jetstream/configuration_mgmt/kubernetes_controller) now fail to be created.

NACK logs these errors when previously existing streams are attempted to be created:
```
E1026 22:30:10.276732       1 controller.go:339] failed to process stream: failed to set "<name>" stream finalizers: Stream.jetstream.nats.io "ingestion-monitoring-attempts-queue" is invalid: [spec.sources: Invalid value: "null": spec.sources in body must be of type array: "null", spec.placement: Invalid value: "null": spec.placement in body must be of type object: "null", spec.mirror: Invalid value: "null": spec.mirror in body must be of type object: "null"]
```

**Comment by wallyqs** [comment]
We will start bumping the versions of the CRDs to avoid this type of incompatibilities, now is at v1beta2.
