### ISSUE TITLE
Jetstream Controller does not support to update stream CRD's “sources” field

### ISSUE THREAD

**Issue by HugoLei** [nats-io/nack#58]
1. Create a stream CRD, for example mystream
2. mystream has "sources" field
3. Jetstream Controller can create a stream named "mystream" with "sources" info in the NATS cluster.
4. Edit the mystream CRD by kubectl, and add another source to the "sources" array
5. Then Jetstream Controller just "delete" the "sources" info from "mystream" in the NATS cluster.

before
![image](https://user-images.githubusercontent.com/29938566/147633773-36d72e3d-7023-479d-9bbe-3dfe3bdc5a8c.png)

edit CRD
![image](https://user-images.githubusercontent.com/29938566/147633847-64199dd1-7202-4e07-8b4f-a4b24804e89e.png)

after
![image](https://user-images.githubusercontent.com/29938566/147633786-e47e673e-277e-48c9-ba0d-9f2506ef760a.png)

**Comment by pacoguzman** [comment]
I've opened a PR to try to solve this issue plus be able to update mirror field too https://github.com/nats-io/nack/pull/99

**Comment by wallyqs** [comment]
Fixed via #99
