### ISSUE TITLE
Stream Template crd not served

### ISSUE THREAD

**Issue by oshkiole** [nats-io/nack#71]
Hi,
While working on a project that was supposed to use stream templates for dynamic stream creation we found out that stream templates are declared in crds file, but marked as not served. Are they not served due to some issue directly in NACK or are they missing version `v1beta2`? Because, as I see, all other resources have versions `v1beta1` and `v1beta2`, but stream templates only have `v1beta1`.
https://github.com/nats-io/nack/blob/552472d50455e84ee5bda90298c0aab1ef0963a7/deploy/crds.yml#L677-L692

**Comment by wallyqs** [comment]
Hi @oshkiole the streamtemplate feature from JetStream does not work in clustering mode so we decided to remove them from the v1beta2 CRDs.

**Comment by oshkiole** [comment]
@wallyqs Thank you for your reply. Do you know does this issue going to be fixed in future? In my project we already moved to a different solution, but this would be good to know.
