### ISSUE TITLE
Docker image for 0.8.0 not published to natsio/nats-server-config-reloader

### ISSUE THREAD

**Issue by liam-verta** [nats-io/nack#96]
Same situation as what happened in #86 but for both `natsio/nats-server-config-reloader` and `natsio/nats-boot-config`. 

v0.8.0 is not available on:
* https://hub.docker.com/r/natsio/nats-boot-config
* https://hub.docker.com/r/natsio/nats-server-config-reloader

v0.8.0 included dependency updates and is built on a later version of Go than v0.7.4, so there should be new versions.

**Comment by liam-verta** [comment]
@wallyqs 
Is there some optimization that is going awry here?

**Comment by wallyqs** [comment]
Thanks for following up @liam-verta, we're changing the way these are published soon to keep them in sync. For now 0.8.0 images of both those images are now available in DockerHub.
